### ISSUE TITLE
Mod no longer work after the v0.21.29 update

### ISSUE THREAD

**Issue by thorinoakenaxe123** [dianchia/DefenseTower#9]
![necessebug](https://user-images.githubusercontent.com/128193015/226066009-eb39c898-23a6-4c09-b1ae-49c723fda1c2.png)
Just constant error after placing one tower down now ever since the update yesterday. If you have existing towers placed on the save file, it would just show you the error message.

**Comment by dianchia** [comment]
Thank you for submitting.

This seems like a version mismatched on the Java runtime used by me during development and the game during runtime.
I am currently working on it and will get back to you soon!

**Comment by thorinoakenaxe123** [comment]
Thanks for fixing that and amazing work.
